---
title: "Usando Pacotes do R para o Manuseio de Dados"
author: "Marcelo Ventura Freire (EACH/USP)"
output: 
  ioslides_presentation: 
    fig_caption: yes
    incremental: no
    transition: faster
---

```{r setup, include=FALSE, eval=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Usando Pacotes do R para o Manuseio de Dados
## O que veremos

- Atividades de Manuseio de Dados
- Pacotes do R para o Manuseio de Dados

# Atividades de Manuseio de Dados
## Atividades de Manuseio de Dados
1. *Piping*
2. Lendo/importando/escrevendo/exportando
3. Visualização dos dados e da sua estrutura
4. Manuseio das variáveis do conjunto de dados
5. Manuseio das observações do conjunto de dados
6. Convertendo entre os formatos longo e largo
7. Manuseio de arquivos
8. *Manuseio das observações e das variáveis*
9. *Agregação os dados de um conjunto de dados*
10. *Junção de conjuntos de dados*

# *Piping*
## *Piping*

1. pacote `magrittr`: %>%, %T>%, %<>%
2. pacote `pipeR`: %>>%


# Lendo, importando, escrevendo, exportando
## Lendo, importando, escrevendo, exportando

1. pacote `base`
    1. save
    2. load
1. pacote `utils`
    1. read.csv, read.csv2, read.delim, read.delim2 e read.table
    2. tar, untar, zip e unzip
1. pacote `foreign`
    1. read.dta (Stata)
    2. read.epiinfo
    3. read.mpt (Minitab)
    4. read.spss
1. pacote `readxl`
    1. excel_sheets
    2. read_excel

## Lendo, importando, escrevendo, exportando
1. pacote `base`
    1. save
    2. load

## Lendo, importando, escrevendo, exportando
1. pacote `utils`
    1. read.csv, read.csv2, read.delim, read.delim2 e read.table
    2. tar, untar, zip e unzip

## Lendo, importando, escrevendo, exportando
1. pacote `foreign`
    1. read.dta (Stata)
    2. read.epiinfo
    3. read.mpt (Minitab)
    4. read.spss

## Lendo, importando, escrevendo, exportando
1. pacote `readxl`
    1. excel_sheets
    2. read_excel


# Visualização dos dados e da sua estrutura
## Visualização dos dados e da sua estrutura

1. pacote `base`
    1. summary, table, 
    2. unique
1. pacote `utils`
    1. str
    2. fix
    3. head e tail

# Manuseio das variáveis do conjunto de dados
## Manuseio das variáveis do conjunto de dados

1. pacote `base`
    is.* (funções de verificação de tipos)
    as.* (funções de conversão de tipos), 
    cut
    ifelse
    gsub
    iconv
    paste e paste0
1. pacote `dplyr`
    select e rename
    mutate e transmute
1. pacote `tidyr`
    separate
    unite
1. pacote `car`
    recode
1. pacote `lubridate` (processamento de strings de data e hora)

# Manuseio das observações do conjunto de dados
## Manuseio das observações do conjunto de dados

1. pacote `base`
    1. grep*
    2. regex*
    3. is.na, is.nan, is.null, is.infinite
    4. any, all
1. pacote `dplyr` 
    1. filter
    2. arrange

# Convertendo entre os formatos longo e largo
## Convertendo entre os formatos longo e largo

1. pacote `reshape2`
    1. melt
    2. cast
    3. acast e dcast
    4. recast
1. pacote `tidyr`
    1. gather
    2. spread

# Manuseio de arquivos
## Manuseio de arquivos

1. pacote `base`
    1. get.wd, set.wd
    2. dir, dir.create, dirnames
    3. list.*
    4. file.*

# *Manuseio das observações e das variáveis*
## *Manuseio das observações e das variáveis*

1. pacote `data.table`

# *Agregação os dados de um conjunto de dados*
## *Agregação os dados de um conjunto de dados*

1. pacote `base`
    1. by
    2. apply, *apply
1. pacote `dplyr`
    1. group_by
    2. summarise

# *Junção de conjuntos de dados*
## *Junção de conjuntos de dados*

1. pacote `base`
    1. cbind, rbind;  
    2. merge
1. pacote `reshape`
    1. merge_all
1. pacote `dplyr`
    1. *_join 
