---
title: "Tratamento e Manuseio de Dados com R"
author: "Marcelo Ventura Freire (EACH/USP)"
output: 
    ioslides_presentation:
        widescreen : true
        self_contained: true
        smart: true
---

```{r setup, include=FALSE, eval=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```





#Tratamento e Manuseio de Dados com R



## Objetivos

Com este curso, eu pretendo que vocês aprendam...

- elaborar um programa básico em `R` de...
    - importação/exportação/leitura/gravação de dados
    - manuseio e crítica de dados
- elaborar um documento em `RMarkdown` que integre texto e código em `R`
- conduzir essas atividades através...
    - do editor integrado `RStudio`
    - do sistema de controle de versão `Git` 
- produzir 
    - análises descritivas básicas
    - gráficos básicos



## Objetivos

Ao final deste curso, eu espero que vocês consigam...

- instalar e rodar os programas `R`, `RStudio`, `Git`, `Pandoc`, `LaTeX`
- realizar no conjunto de dados da sua pesquisa/iniciação/monografia/dissertação/tese
    - importação, exportação, leitura e gravação 
    - tratamento, limpeza e formatação do seu conjunto de dados
    - documentação do seu conjunto de dadosdo seu conjunto de dados



## Para Acompanhar as Aulas

Estas transparências estão no *site* <http://github.com/zyxdef/>.

Entre no Projeto `TrataDadoR` no *site* <https://github.com/zyxdef/> e procure 
pelo *link* para as transparências.



## O que veremos

1. [Instalando e Rodando o Básico](#instalando-e-rodando-o-basico)
1. [Princípios de Tratamento e Manuseio de Dados](#7)
1. [Uma Proposta de *Workflow* Mínimo para Manuseio de Dados em R](#8)
1. [Rudimentos da Linguagem R](#9)
1. [Usando Pacotes do R para o Manuseio dos Dados](#10)
1. [Implementando o *Workflow* Proposto](#11)





# Instalando e Rodando o Básico

Vá para a apresentação  
[Instalando e Rodando o Básico](InstalaR/instalando.rodando.R.html)






# Princípios de Tratamento e Manuseio de Dados

Vá para a apresentação  
[Princípios de Tratamento e Manuseio de Dados](PrincipTratDados/principios.tratamento.dado.html)







# Uma Proposta de *Workflow* Mínimo para Manuseio de Dados em R
Vá para a apresentação  
[Uma Proposta de *Workflow* Mínimo para Manuseio de Dados em R](MinWokflowManusDados/workflow.html)





# Rudimentos da Linguagem R

Vá para a apresentação  
[Rudimentos da Linguagem R](IntroLingR/rudimentos.linguagem.R.html)






# Usando Pacotes do R para o Manuseio dos Dados

Vá para a apresentação  
[Usando Pacotes do R para o Manuseio de Dados](PacRManusDados/pacotes.manuseio.dados.R.html)







# Implementando o *Workflow* Proposto
Vá para a apresentação  
[Implementando o *Workflow* Proposto](MinWokflowManusDados/workflow.html)

